name: Portfolio CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install HTML validator
        run: |
          npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint "**/*.html"

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress "./**/*.html"
